version: 3.5.{build}
image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Appveyor"

# disable built-in tests.
test: off

artifacts:
- path: output\*.nupkg

environment:
  MYGET_API_KEY:
    secure: wtAvJDVl2tfwiVcyLExFHLvZVfUWiQRHsfdHBFCNEATeCHo1Nd8JP642PfY8xhji
  NUGET_API_KEY:
    secure: 3ojZLs9hiHk/7047hiirFk/qG2RxUACmA8DAUk+8AoILr5R7c4tDGXeTsBjjhq5h
  CHOCO_API_KEY:
    secure: aDsu1U+umVYFVybjkBVtVQsatSj3QKbD7VkGQci9mNF3493g9Giao/GABISIaHjT
  GITHUB_ACCESS_TOKEN:
    secure: xmGXWrw5Nj3CI3fPxhw/DWIU5YL/1mM06pSmjpkd9LpKs3t3EYXbECbEQs62lU/O
